autenticacao/urls.py
from django.urls import path
from . import views

app_name = 'autenticacao'

urlpatterns = [
    path('', views.login, name='login'),
    path('get_perfis/', views.get_perfis, name='get_perfis'),
    path('logout/', views.logout, name='logout'),
    path('recuperar-senha/', views.recuperar_senha, name='recuperar-senha'),
    path('resetar-senha/<str:token>/', views.resetar_senha, name='resetar-senha'),
    path('cadastro/', views.criar_usuario, name='cadastro_usuario'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('autenticacao.urls')),
    path('core/', include('core.urls')),
]

core/urls.py
from django.urls import path, include
from . import views

app_name="core"

urlpatterns = [
    path('main', views.main, name='main'),
]

autenticacao/models.py
from django.db import models

# Create your models here.

autenticacao/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login as auth_login, logout as auth_logout
from cadastros.models import Usuario
from django.contrib import messages
from django.http import JsonResponse
from django.core.mail import send_mail, EmailMessage
from django.shortcuts import render, redirect
from django.core.mail import send_mail
from django.contrib.auth.models import User
from django.contrib.auth.hashers import make_password
from django.utils.crypto import get_random_string
from django.http import HttpResponse
from django.shortcuts import render, redirect
from cadastros.forms import UsuarioCreationForm
from django.contrib import messages
from django.core.cache import cache


def criar_usuario(request):
    if request.method == 'POST':
        form = UsuarioCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Usuário criado com sucesso!')
            return redirect('autenticacao:login')  # Redireciona para alguma página
    else:
        form = UsuarioCreationForm()

    return render(request, 'criar_usuario.html', {'form': form})


TOKENS = {}

def recuperar_senha(request):
    if request.method == 'POST':
        email = request.POST.get('email')
        try:
            user = Usuario.objects.get(email=email)
            token = get_random_string(32)  # Gera um token aleatório
            cache.set(token, email, timeout=3600)  # Expira em 1 hora
            send_mail(
                'Recuperação de senha',
                f'Use este link para redefinir sua senha: '
                f'http://127.0.0.1:8000/resetar-senha/{token}/',
                'seuemail@exemplo.com',
                [email],
            )
            messages.success(request, 'E-mail enviado com sucesso.')
            return redirect('autenticacao:login')
        except Usuario.DoesNotExist:
            messages.error(request, 'E-mail não encontrado.')
            return redirect('autenticacao:login')

    return render(request, 'recuperar_senha.html')


def resetar_senha(request, token):
    if request.method == 'POST':
        nova_senha = request.POST.get('senha')
        email = cache.get(token)  # Recupera o e-mail associado ao token
        if email:
            try:
                user = Usuario.objects.get(email=email)
                user.password = make_password(nova_senha)
                user.save()
                cache.delete(token)  # Remove o token após o uso
                messages.success(request, 'Senha alterada com sucesso.')
                return redirect('autenticacao:login')
            except Usuario.DoesNotExist:
                messages.error(request, 'Usuário não encontrado.')
                return redirect('autenticacao:login')
        messages.error(request, 'Token inválido ou expirado.')
        return redirect('autenticacao:login')
    return render(request, 'resetar_senha.html', {'token': token})


def login(request):
    if request.method == 'POST':
        email = request.POST.get('txtEmail')
        senha = request.POST.get('txtSenha')
        perfil_id = request.POST.get('slcPerfil')

        usuario = authenticate(request, username=email, password=senha)

        if usuario is not None and perfil_id:
            perfis_usuario = usuario.perfis.filter(id=perfil_id)
            if perfis_usuario.exists():

                request.session.flush()
                auth_login(request, usuario)

                request.session['id_atual'] = usuario.id
                request.session['email_atual'] = usuario.email
                request.session['departamento_id_atual'] = usuario.departamento.id
                request.session['departamento_nome_atual'] = usuario.departamento.nome
                request.session['departamento_sigla_atual'] = usuario.departamento.sigla
                request.session['perfil_atual'] = perfis_usuario.first().nome
                request.session['perfis'] = list(usuario.perfis.values_list('nome',flat=True))
                request.session.set_expiry(14400)

                messages.success(request, 'Login realizado com sucesso!')

                if request.session.get('perfil_atual') in {'Administrador', 'Estoquista', 'Vendedor'}:
                    return redirect('core:main')
            else:
                messages.error(request, 'Perfil inválido!')
        else:
            if usuario is None:
                messages.error(request, 'Senha incorreta!')
            else:
                messages.error(request, 'Usuário ou Senha inválido!')

    return render(request, 'login.html')

def get_perfis(request):
    email = request.GET.get('email', '')
    perfis = []

    if Usuario.objects.filter(email=email).exists():
        usuario = Usuario.objects.get(email=email)
        perfis = usuario.perfis.all().values('id', 'nome')
        data = {'perfis': list(perfis), 'usuario_existe': True}
    else:
        data = {'usuario_existe': False}

    return JsonResponse(data)

def logout(request):
    request.session.flush()
    auth_logout(request)
    messages.success(request, 'Logout realizado com sucesso!')
    return redirect('autenticacao:login')

autenticacao/templates/criar_usuario.html
{% extends 'index.html' %}

{% block conteudo%}

<h2>Criar Usuário</h2>
  <form method="POST">
    {% csrf_token %}
    {{ form.as_p }}  <!-- Exibe o formulário em formato de parágrafos -->
    <button type="submit">Criar Usuário</button>
  </form>
  
{% endblock %}

autenticacao/templates/login.html
{% extends 'index.html' %} {% block conteudo %}
<div class="container">
    <h2>Login</h2>
    <form method="POST" action="{% url 'autenticacao:login' %}">
        {% csrf_token %}
        <div class="form-group">
            <label for="txtEmail">E-mail</label>
            <input type="email" class="form-control" id="txtEmail" name="txtEmail" required autocomplete="off" />
            <div id="divEmailError" class="error-message"></div>
        </div>
        <div class="form-group hidden-group" id="divSenha">
            <label for="txtSenha">Senha</label>
            <input
                type="password"
                class="form-control"
                id="txtSenha"
                name="txtSenha"
                required
                autocomplete="new-password"
            />
        </div>
        <div class="form-group hidden-group" id="divPerfil">
            <label for="perfil">Perfil</label>
            <select class="form-control" id="slcPerfil" name="slcPerfil" required></select>
        </div>
        <div id="divSpace" class="space"></div>
        <button type="submit" class="btn btn-light">Entrar</button><br />
        <a id="btnEsqueciSenha" class="btn btn-light" style="margin-top: 10px">Esqueci minha senha</a>
    </form>
</div>

<div
    class="modal fade"
    id="modalSenha"
    tabindex="-1"
    role="dialog"
    aria-labelledby="modalSenhaLabel"
    aria-hidden="true"
>
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="modalSenhaLabel">Recuperar Senha</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body text-center">
                <form id="formRecuperarSenha" method="post" action="{% url 'autenticacao:recuperar-senha' %}">
                    {% csrf_token %}
                    <label for="email">E-mail:</label>
                    <input type="email" id="email" name="email" required />
                    <button type="submit">Enviar</button>
                </form>
            </div>
        </div>
    </div>
</div>

<script>
    $(document).ready(function () {
        $('#formRecuperarSenha').on('submit', function (event) {
            event.stopPropagation(); // Impede que o evento "submit" propague para outros elementos.
        });

        $('#txtEmail').on('input', function () {
            var email = $(this).val();
            $('#divPerfil').addClass('hidden-group');
            $('#divSenha').addClass('hidden-group');
            $('#slcPerfil').empty();
            $('#divEmailError').text(' ').removeClass('visible');

            if (email.length > 0) {
                $.ajax({
                    url: "{% url 'autenticacao:get_perfis' %}",
                    data: { email: email },
                    success: function (data) {
                        $('#slcPerfil').empty();
                        data.perfis.forEach(function (perfil) {
                            $('#slcPerfil').append(new Option(perfil.nome, perfil.id));
                        });
                        $('#divPerfil').removeClass('hidden-group');
                        $('#divSenha').removeClass('hidden-group');
                        $('#divEsqueceuSenha').removeClass('hidden-group');

                        $('#divEmailError').text('.').addClass('visible');
                    },
                });
            }
        });
    });

    $('#btnEsqueciSenha').click(function () {
        $('#modalSenha').modal('show');
    });
</script>
{% endblock %}

autenticacao/templates/recuperar_senha.html
{% extends 'index.html' %}

{% block conteudo%}

<h2>Recuperar Senha</h2>
    <form method="post">
        {% csrf_token %}
        <label for="email">E-mail:</label>
        <input type="email" id="email" name="email" required>
        <button type="submit">Enviar</button>
    </form>

{% endblock %}

autenticacao/templates/resetar_senha.html
{% extends 'index.html' %}

{% block conteudo%}

<h2>Redefinir Senha</h2>
    <form method="post">
        {% csrf_token %}
        <input type="hidden" name="token" value="{{ token }}">
        <label for="senha">Nova Senha:</label>
        <input type="password" id="senha" name="senha" required>
        <button type="submit">Alterar Senha</button>
    </form>

{% endblock %}